=== mrrishit909/climate-signal-observatory/data/contracts/coastlines.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "additionalProperties": false,
 "properties": {
  "coords": {
   "items": {
    "type": "number"
   },
   "minItems": 100,
   "type": "array"
  },
  "layout": {
   "type": "string"
  },
  "n_lines": {
   "type": "integer"
  },
  "n_points": {
   "type": "integer"
  },
  "schema_version": {
   "const": "v1"
  },
  "source": {
   "additionalProperties": false,
   "properties": {
    "file": {
     "type": "string"
    },
    "license": {
     "type": "string"
    },
    "name": {
     "type": "string"
    },
    "url": {
     "type": "string"
    }
   },
   "required": [
    "name",
    "url",
    "license",
    "file"
   ],
   "type": "object"
  },
  "starts": {
   "items": {
    "type": "integer"
   },
   "minItems": 1,
   "type": "array"
  },
  "tags": {
   "additionalProperties": {
    "pattern": "^(OBSERVED|DERIVED|PREDICTED|SIMULATED|SYNTHETIC)(/(OBSERVED|DERIVED|PREDICTED|SIMULATED|SYNTHETIC))*$",
    "type": "string"
   },
   "minProperties": 1,
   "type": "object"
  }
 },
 "required": [
  "schema_version",
  "tags",
  "source",
  "layout",
  "n_lines",
  "n_points",
  "starts",
  "coords"
 ],
 "title": "coastlines",
 "type": "object"
}

=== mrrishit909/climate-signal-observatory/site/public/data/coastlines.json
{"coords":[-163.71,-78.6,-163.11,-78.22,-161.25,-78.38,-160.25,-78.69,-159.48,-79.05,-159.21,-79.5,-161.13,-79.63,-162.44,-79.28,-163.03,-78.93,-163.07,-78.87,-163.71,-78.6,-6.2,53.87,-6.03,53.15,-6.79,52.26,-8.56,51.67,-9.98,51.82,-9.17,52.86,-9.69,53.88,-8.33,54.66,-7.57,55.13,-6.73,55.17,-5.66,54.55,-6.2,53.87,141.0,-2.6,142.74,-3.29,144.58,-3.86,145.27,-4.37,145.83,-4.88,145.98,-5.47,147.65,-6.08,147.89,-6.61,146.97,-6.72,147.19,-7.39,148.08,-8.04,148.73,-9.1,149.31,-9.07,149.27,-9.51,150.04,-9.68,149.74,-9.87,150.8,-10.29,150.69,-10.58,150.03,-10.65,149.78,-10.39,148.92,-10.28,147.91,-10.13,147.14,-9.49,146.57,-8.94,146.05,-8.07,144.74,-7.63,143.9,-7.92,143.29,-8.25,143.41,-8.98,142.63,-9.33,142.07,-9.16,141.03,-9.12,140.14,-8.3,139.13,-8.1,138.88,-8.38,137.61,-8.41,138.04,-7.6,138.67,-7.32,138.41,-6.23,137.93,-5.39,135.99,-4.55,135.16,-4.46,133.66,-3.54,133.37,-4.02,132.98,-4.11,132.76,-3.75,132.75,-3.31,131.99,-2.82,133.07,-2.46,133.78,-2.48,133.7,-2.21,132.23,-2.21,131.84,-1.62,130.94,-1.43,130.52,-0.94,131.87,-0.7,132.38,-0.37,133.99,-0.78,134.14,-1.15,134.42,-2.77,135.46,-3.37,136.29,-2.31,137.44,-1.7,138.33,-1.7,139.18,-2.05,139.93,-2.41,141.0,-2.6,114.2,4.53,114.6,4.9,115.45,5.45,116.22,6.14,116.73,6.92,117.13,6.93,117.64,6.42,117.69,5.99,118.35,5.71,119.18,5.41,119.11,5.02,118.44,4.97,118.62,4.48,117.88,4.14,117.31,3.23,118.05,2.29,117.88,1.83,119.0,0.9,117.81,0.78,117.48,0.1,117.52,-0.8,116.56,-1.49,116.53,-2.48,116.15,-4.01,116.0,-3.66,114.86,-4.11,114.47,-3.5,113.76,-3.44,113.26,-3.12,112.07,-3.48,111.7,-2.99,111.05,-3.05,110.22,-2.93,110.07,-1.59,109.57,-1.31,109.09,-0.46,108.95,0.42,109.07,1.34,109.66,2.01,110.4,1.66,111.17,1.85,111.37,2.7,111.8,2.89,113.0,3.1,113.71,3.89,114.2,4.53,-93.61,74.98,-94.16,74.59,-95.61,74.67,-96.82,74.93,-96.29,75.38,-94.85,75.65,-93.98,75.3,-93.61,74.98,-93.84,77.52,-94.3,77.49,-96.17,77.56,-96.44,77.83,-94.42,77.82,-93.72,77.63,-93.84,77.52,-96.75,78.77,-95.56,78.42,-95.83,78.06,-97.31,77.85,-98.12,78.08,-98.55,78.46,-98.63,78.87,-97.34,78.83,-96.75,78.77,-88.15,74.39,-89.76,74.52,-92.42,74.84,-92.77,75.39,-92.89,75.88,-93.89,76.32,-95.96,76.44,-97.12,76.75,-96.75,77.16,-94.68,77.1,-93.57,76.78,-91.61,76.78,-90.74,76.45,-90.97,76.07,-89.82,75.85,-89.19,75.61,-87.84,75.57,-86.38,75.48,-84.79,75.7,-82.75,75.78,-81.13,75.71,-80.06,75.34,-79.83,74.92,-80.46,74.66,-81.95,74.44,-83.23,74.56,-86.1,74.41,-88.15,74.39,-111.26,78.15,-109.85,78.0,-110.19,77.7,-112.05,77.41,-113.53,77.73,-112.72,78.05,-111.26,78.15,-110.96,78.8,-109.66,78.6,-110.88,78.41,-112.54,78.41,-112.53,78.55,-111.5,78.85,-110.96,78.8,-66.28,18.51,-65.77,18.43,-65.59,18.23,-65.85,17.98,-66.6,17.98,-67.18,17.95,-67.24,18.37,-67.1,18.52,-66.28,18.51,-77.57,18.49,-76.9,18.4,-76.37,18.16,-76.2,17.89,-76.9,17.87,-77.21,17.7,-77.77,17.86,-78.34,18.23,-78.22,18.45,-77.8,18.52,-77.57,18.49,-82.27,23.19,-81.4,23.12,-80.62,23.11,-79.68,22.77,-79.28,22.4,-78.35,22.51,-77.99,22.28,-77.15,21.66,-76.52,21.21,-76.19,21.22,-75.6,21.02,-75.67,20.74,-74.93,20.69,-74.18,20.28,-74.3,20.05,-74.96,19.92,-75.63,19.87,-76.32,19.95,-77.76,19.86,-77.09,20.41,-77.49,20.67,-78.14,20.74,-78.48,21.03,-78.72,21.6,-79.28,21.56,-80.22,21.83,-80.52,22.04,-81.82,22.19,-82.17,22.39,-81.8,22.64,-82.78,22.69,-83.49,22.17,-83.91,22.15,-84.05,21.91,-84.55,21.8,-84.97,21.9,-84.45,22.2,-84.23,22.57,-83.78,22.79,-83.27,22.98,-82.51,23.08,-82.27,23.19,-55.6,51.32,-56.13,50.69,-56.8,49.81,-56.14,50.15,-55.47,49.94,-55.82,49.59,-54.94,49.31,-54.47,49.56,-53.48,49.25,-53.79,48.52,-53.09,48.69,-52.96,48.16,-52.65,47.54,-53.07,46.66,-53.52,46.62,-54.18,46.81,-53.96,47.63,-54.24,47.75,-55.4,46.88,-56.0,46.92,-55.29,47.39,-56.25,47.63,-57.33,47.57,-59.27,47.6,-59.42,47.9,-58.8,48.25,-59.23,48.52,-58.39,49.13,-57.36,50.72,-56.74,51.29,-55.87,51.63,-55.41,51.59,-55.6,51.32,-83.88,65.11,-82.79,64.77,-81.64,64.46,-81.55,63.98,-80.82,64.06,-80.1,63.73,-80.99,63.41,-82.55,63.65,-83.11,64.1,-84.1,63.57,-85.52,63.05,-85.87,63.64,-87.22,63.54,-86.35,64.04,-86.22,64.82,-85.88,65.74,-85.16,65.66,-84.98,65.22,-84.46,65.37,-83.88,65.11,-78.77,72.35,-77.82,72.75,-75.61,72.24,-74.23,71.77,-74.1,71.33,-72.24,71.56,-71.2,70.92,-68.79,70.53,-67.91,70.12,-66.97,69.19,-68.81,68.72,-66.45,68.07,-64.86,67.85,-63.42,66.93,-61.85,66.86,-62.16,66.16,-63.92,65.0,-65.15,65.43,-66.72,66.39,-68.02,66.26,-68.14,65.69,-67.09,65.11,-65.73,64.65,-65.32,64.38,-64.67,63.39,-65.01,62.67,-66.28,62.95,-68.78,63.75,-67.37,62.88,-66.33,62.28,-66.17,61.93,-68.88,62.33,-71.02,62.91,-72.24,63.4,-71.89,63.68,-73.38,64.19,-74.83,64.68,-74.82,64.39,-77.71,64.23,-78.56,64.57,-77.9,65.31,-76.02,65.33,-73.96,65.45,-74.29,65.81,-73.94,66.31,-72.65,67.28,-72.93,67.73,-73.31,68.07,-74.84,68.55,-76.87,68.89,-76.23,69.15,-77.29,69.77,-78.17,69.83,-78.96,70.17,-79.49,69.87,-81.31,69.74,-84.94,69.97,-87.06,70.26,-88.68,70.41,-89.51,70.76,-88.47,71.22,-89.89,71.22,-90.21,72.24,-89.44,73.13,-88.41,73.54,-85.83,73.8,-86.56,73.16,-85.77,72.53,-84.85,73.34,-82.32,73.75,-80.6,72.72,-80.75,72.06,-78.77,72.35,-94.5,74.13,-92.42,74.1,-90.51,73.86,-92.0,72.97,-93.2,72.77,-94.27,72.02,-95.41,72.06,-96.03,72.94,-96.02,73.44,-95.5,73.86,-94.5,74.13,-100.44,72.71,-101.54,73.36,-100.36,73.84,-99.16,73.63,-97.38,73.76,-97.12,73.47,-98.05,72.99,-96.54,72.56,-96.72,71.66,-98.36,71.27,-99.32,71.36,-100.01,71.74,-102.48,72.48,-102.48,72.83,-100.44,72.71,-107.82,75.85,-106.93,76.01,-105.88,75.97,-105.7,75.48,-106.31,75.01,-109.7,74.85,-112.22,74.42,-113.74,74.39,-113.87,74.72,-111.79,75.16,-116.31,75.04,-117.71,75.22,-116.35,76.2,-115.4,76.48,-112.59,76.14,-110.81,75.55,-109.07,75.47,-110.5,76.43,-109.58,76.79,-108.55,76.68,-108.21,76.2,-107.82,75.85,-122.85,76.12,-121.16,76.86,-119.1,77.51,-117.57,77.5,-116.2,77.65,-116.34,76.88,-117.11,76.53,-118.04,76.48,-119.9,76.05,-121.5,75.9,-122.85,76.12,-121.54,74.45,-120.11,74.24,-117.56,74.19,-116.58,73.9,-115.51,73.48,-116.77,73.22,-119.22,72.52,-120.46,71.82,-120.46,71.38,-123.09,70.9,-123.62,71.34,-125.93,71.87,-125.5,72.29,-124.81,73.02,-123.94,73.68,-124.92,74.29,-121.54,74.45,-166.47,60.38,-165.67,60.29,-165.58,59.91,-166.19,59.75,-166.85,59.94,-167.46,60.21,-166.47,60.38,-153.23,57.97,-152.56,57.9,-152.14,57.59,-153.01,57.12,-154.01,56.73,-154.52,56.99,-154.67,57.46,-153.76,57.82,-153.23,57.97,-132.71,54.04,-131.75,54.12,-132.05,52.98,-131.18,52.18,-131.58,52.18,-132.18,52.64,-132.55,53.1,-133.05,53.41,-133.24,53.85,-133.18,54.17,-132.71,54.04,-125.42,49.95,-124.92,49.48,-123.92,49.06,-123.51,48.51,-124.01,48.37,-125.66,48.83,-125.95,49.18,-126.85,49.53,-127.03,49.81,-128.06,49.99,-128.44,50.54,-128.36,50.77,-127.31,50.55,-126.69,50.4,-125.76,50.3,-125.42,49.95,-171.73,63.78,-171.11,63.59,-170.49,63.69,-169.68,63.43,-168.69,63.3,-168.77,63.19,-169.53,62.98,-170.29,63.19,-170.67,63.38,-171.55,63.32,-171.79,63.41,-171.73,63.78,-105.49,79.3,-103.53,79.17,-100.83,78.8,-100.06,78.32,-99.67,77.91,-101.3,78.02,-102.95,78.34,-105.18,78.38,-104.21,78.68,-105.42,78.92,-105.49,79.3,32.95,35.39,33.67,35.37,34.58,35.67,33.9,35.25,34.0,34.98,32.98,34.57,32.49,34.7,32.26,35.1,32.8,35.15,32.95,35.39,26.29,35.3,26.16,35.0,24.72,34.92,24.74,35.08,23.51,35.28,23.7,35.71,24.25,35.37,25.03,35.42,25.77,35.35,25.75,35.18,26.29,35.3,49.54,-12.47,49.81,-12.9,50.06,-13.56,50.22,-14.76,50.48,-15.23,50.38,-15.71,50.2,-16.0,49.86,-15.41,49.67,-15.71,49.86,-16.45,49.77,-16.88,49.5,-17.11,49.44,-17.95,49.04,-19.12,48.55,-20.5,47.93,-22.39,47.55,-23.78,47.1,-24.94,46.28,-25.18,45.41,-25.6,44.83,-25.35,44.04,-24.99,43.76,-24.46,43.7,-23.57,43.35,-22.78,43.25,-22.06,43.43,-21.34,43.89,-21.16,43.9,-20.83,44.37,-20.07,44.46,-19.44,44.23,-18.96,44.04,-18.33,43.96,-17.41,44.31,-16.85,44.45,-16.22,44.94,-16.18,45.5,-15.97,45.87,-15.79,46.31,-15.78,46.88,-15.21,47.71,-14.59,48.01,-14.09,47.87,-13.66,48.29,-13.78,48.85,-13.09,48.86,-12.49,49.19,-12.04,49.54,-12.47,167.22,-15.89,167.84,-16.47,167.52,-16.6,167.18,-16.16,167.22,-15.89,166.79,-15.67,166.65,-15.39,166.63,-14.63,167.11,-14.93,167.27,-15.74,167.0,-15.61,166.79,-15.67,134.21,-6.9,134.11,-6.14,134.29,-5.78,134.5,-5.45,134.73,-5.74,134.72,-6.21,134.21,-6.9,-48.66,-78.05,-48.15,-78.05,-46.66,-77.83,-45.15,-78.05,-43.92,-78.48,-43.49,-79.09,-43.37,-79.52,-43.33,-80.03,-44.88,-80.34,-46.51,-80.59,-48.39,-80.83,-50.48,-81.03,-52.85,-80.97,-54.16,-80.63,-53.99,-80.22,-51.85,-79.95,-50.99,-79.61,-50.36,-79.18,-49.91,-78.81,-49.31,-78.46,-48.66,-78.05,-66.29,-80.26,-64.04,-80.29,-61.88,-80.39,-61.14,-79.98,-60.61,-79.63,-59.57,-80.04,-59.87,-80.55,-60.16,-81.0,-62.26,-80.86,-64.49,-80.92,-65.74,-80.59,-65.74,-80.55,-66.29,-80.26,-73.92,-71.27,-73.23,-71.15,-72.07,-71.19,-71.78,-70.68,-71.72,-70.31,-71.74,-69.51,-71.17,-69.04,-70.25,-68.88,-69.72,-69.25,-69.49,-69.62,-69.06,-70.07,-68.73,-70.51,-68.45,-70.96,-68.33,-71.41,-68.51,-71.8,-68.78,-72.17,-69.96,-72.31,-71.08,-72.5,-72.39,-72.48,-71.9,-72.09,-73.07,-72.23,-74.19,-72.37,-74.95,-72.07,-75.01,-71.66,-73.92,-71.27,-102.33,-71.89,-101.7,-71.72,-100.43,-71.85,-98.98,-71.93,-97.88,-72.07,-96.79,-71.95,-96.2,-72.52,-96.98,-72.44,-98.2,-72.48,-99.43,-72.44,-100.78,-72.5,-101.8,-72.31,-102.33,-71.89,-122.62,-73.66,-122.41,-73.32,-121.21,-73.5,-119.92,-73.66,-118.72,-73.48,-119.29,-73.83,-120.23,-74.09,-121.62,-74.01,-122.62,-73.66,-127.28,-73.46,-126.56,-73.25,-125.56,-73.48,-124.03,-73.87,-124.62,-73.83,-125.91,-73.74,-127.28,-73.46,165.78,-21.08,166.6,-21.7,167.12,-22.16,166.74,-22.4,166.19,-22.13,165.47,-21.68,164.83,-21.15,164.17,-20.44,164.03,-20.11,164.46,-20.12,165.02,-20.46,165.46,-20.8,165.78,-21.08,152.64,-3.66,153.02,-3.98,153.14,-4.5,152.83,-4.77,152.64,-4.18,152.41,-3.79,151.95,-3.46,151.38,-3.04,150.66,-2.74,150.94,-2.5,151.48,-2.78,151.82,-3.0,152.24,-3.24,152.64,-3.66,151.3,-5.84,150.75,-6.08,150.24,-6.32,149.71,-6.32,148.89,-6.03,148.32,-5.75,148.4,-5.44,149.3,-5.58,149.85,-5.51,150.0,-5.03,150.14,-5.0,150.24,-5.53,150.81,-5.46,151.09,-5.11,151.65,-4.76,151.54,-4.17,152.14,-4.15,152.34,-4.31,152.32,-4.87,151.98,-5.48,151.46,-5.56,151.3,-5.84,162.12,-10.48,162.4,-10.83,161.7,-10.82,161.32,-10.2,161.
